# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ndata.proto\"#\n\x0cImageRequest\x12\x13\n\x0bimageBuffer\x18\x01 \x02(\t\"!\n\nCheckReply\x12\x13\n\x0b\x63heckResult\x18\x01 \x02(\t29\n\x07Greeter\x12.\n\x0e\x43heckImageFace\x12\r.ImageRequest\x1a\x0b.CheckReply\"\x00')
)




_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageBuffer', full_name='ImageRequest.imageBuffer', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=49,
)


_CHECKREPLY = _descriptor.Descriptor(
  name='CheckReply',
  full_name='CheckReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='checkResult', full_name='CheckReply.checkResult', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['CheckReply'] = _CHECKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:ImageRequest)
  ))
_sym_db.RegisterMessage(ImageRequest)

CheckReply = _reflection.GeneratedProtocolMessageType('CheckReply', (_message.Message,), dict(
  DESCRIPTOR = _CHECKREPLY,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:CheckReply)
  ))
_sym_db.RegisterMessage(CheckReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Greeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=86,
  serialized_end=143,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckImageFace',
    full_name='Greeter.CheckImageFace',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_CHECKREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
