# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_pb2 as data__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CheckImageFace = channel.unary_unary(
        '/Greeter/CheckImageFace',
        request_serializer=data__pb2.ImageRequest.SerializeToString,
        response_deserializer=data__pb2.CheckReply.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CheckImageFace(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CheckImageFace': grpc.unary_unary_rpc_method_handler(
          servicer.CheckImageFace,
          request_deserializer=data__pb2.ImageRequest.FromString,
          response_serializer=data__pb2.CheckReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
